services:
  # Backend Service
  - type: web
    name: channelfunding-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: channelfunding
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /api/channels

  # Frontend Service  
  - type: web
    name: channelfunding-frontend
    env: static
    region: singapore
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web
          name: channelfunding-backend
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
