services:
  # Backend Service
  - type: web
    name: channelfunding-backend
    runtime: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: channelfunding
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"

# Note: Frontend must be deployed manually as a Static Site
# Use this build command: npm install --legacy-peer-deps && npm run build
